graph LR
    E1[Eureka 1]
    E2[Eureka 2]
    E3[Eureka 3]
    LB[HAProxy/NGINX]

    E1 <-->|Replica| E2
    E2 <-->|Replica| E3
    E3 <-->|Replica| E1

    LB -->|Tráfico| E1
    LB -->|Tráfico| E2
    LB -->|Tráfico| E3

    subgraph Zona1
        E1
    end

    subgraph Zona2
        E2
    end

    subgraph Zona3
        E3
    end
