sequenceDiagram
    participant C as Cliente
    participant E as Eureka Server
    participant S as Servicio

    S->>E: Registra (POST /eureka/apps/{APP})
    E-->>S: Confirma Registro
    
    loop Heartbeat
        S->>E: Renovar Lease (PUT /eureka/apps/{APP}/{ID})
        E-->>S: Confirma Renovación
    end
    
    C->>E: Consulta Servicios (GET /eureka/apps)
    E-->>C: Lista de Servicios Disponibles
    
    C->>E: Consulta Específica (GET /eureka/apps/{APP})
    E-->>C: Detalles del Servicio
    
    Note over C,S: El cliente puede ahora comunicarse directamente con el servicio
    
    opt Servicio No Responde
        E->>S: Verificar Estado
        S--xE: Sin Respuesta
        E->>E: Elimina Registro
    end
